"""T009 — physical <-> lattice conversion, and masks from PNG / SVG.

Covers ``lbm/units.py`` (``LatticeUnits``) and the two image sources added to
``lbm/geometry.py`` (``from_png``, ``from_svg``), one or more tests per
acceptance criterion in ``old-Docs/TASKS1.md`` § T009.

The committed test image
------------------------
``tests/data/test_body.png`` is generated by :func:`write_test_png` below —
the source of the image lives in this file so its solid-cell count is
*derivable arithmetic* rather than a magic number someone measured once and
nobody can re-check. Regenerate it with::

    myenv/Scripts/python.exe -c "import tests.test_units as t; t.write_test_png()"

Two opaque shapes on a transparent background, chosen so the expected count is
a sum of exact areas: a disc of radius :data:`PNG_RADIUS` and a rectangle of
:data:`PNG_RECT`, which do not overlap. Downscaling by an integer factor with a
box filter preserves area, so the expected cell count is the pixel area times
the area scale — see :func:`expected_solid_cells`.
"""

from __future__ import annotations

import math
import warnings
from pathlib import Path

import numpy as np
import pytest

from lbm.geometry import MaskWarning, bounding_box, from_png, from_svg, min_thickness
from lbm.units import (
    BLUFF_BODY_SPEEDUP,
    TAU_FLOOR,
    U_LATTICE_MAX,
    LatticeUnits,
)

DATA = Path(__file__).parent / "data"
PNG_PATH = DATA / "test_body.png"

# --- the committed test image, as arithmetic ---------------------------------

PNG_SIZE = 256  # pixels, square
PNG_CENTRE = (128.0, 128.0)  # (x, y) in pixels
PNG_RADIUS = 64.0  # pixels
PNG_RECT = (200, 40, 240, 60)  # (x0, y0, x1, y1), half-open, pixels
GRID = (128, 128)  # (ny, nx) the tests load it onto — exactly half


def expected_solid_cells(ny: int = GRID[0], nx: int = GRID[1]) -> float:
    """Solid cells the image *should* produce on an ``(ny, nx)`` grid.

    Area is preserved by a box-filter resample followed by a 0.5 threshold, so
    this is the pixel area of the two shapes times the area scale factor. The
    disc contributes ``pi r^2`` and the rectangle ``w * h``; they do not
    overlap by construction.
    """
    disc = math.pi * PNG_RADIUS**2
    x0, y0, x1, y1 = PNG_RECT
    rect = (x1 - x0) * (y1 - y0)
    scale = (ny / PNG_SIZE) * (nx / PNG_SIZE)
    return (disc + rect) * scale


def write_test_png(path: Path = PNG_PATH) -> Path:
    """Generate ``tests/data/test_body.png``. The source of the committed image.

    RGBA: a white disc and a white rectangle at full alpha on a fully
    transparent background, so ``from_png`` takes the **alpha** path.
    """
    from PIL import Image

    path.parent.mkdir(parents=True, exist_ok=True)
    y, x = np.mgrid[0:PNG_SIZE, 0:PNG_SIZE].astype(np.float64)
    cx, cy = PNG_CENTRE
    disc = (x - cx) ** 2 + (y - cy) ** 2 <= PNG_RADIUS**2
    x0, y0, x1, y1 = PNG_RECT
    rect = (x >= x0) & (x < x1) & (y >= y0) & (y < y1)
    solid = disc | rect

    rgba = np.zeros((PNG_SIZE, PNG_SIZE, 4), dtype=np.uint8)
    rgba[..., :3] = 255
    rgba[..., 3] = np.where(solid, 255, 0)
    Image.fromarray(rgba, mode="RGBA").save(path, optimize=True)
    return path


def load_png(**kwargs) -> np.ndarray:
    """``from_png`` on the committed image, quiet, checks off unless asked."""
    kwargs.setdefault("check", False)
    kwargs.setdefault("verbose", False)
    return from_png(PNG_PATH, GRID, **kwargs)


# --- LatticeUnits: the derivation --------------------------------------------


def test_from_physical_returns_every_derived_quantity():
    """dx, dt, tau, lattice U and Re, all five, from one physical description."""
    u = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, nu_phys=1e-3, cells_per_length=60.0, u_lattice=0.05
    )
    assert u.Re == pytest.approx(1.0 * 0.1 / 1e-3)
    assert u.dx == pytest.approx(0.1 / 60.0)
    assert u.dt == pytest.approx(0.05 * (0.1 / 60.0) / 1.0)
    assert u.U == 0.05
    assert u.tau == pytest.approx(0.5 + 3.0 * 0.05 * 60.0 / u.Re)


def test_tau_matches_the_two_forms_of_the_lattice_viscosity():
    """``nu_phys dt / dx^2`` and ``(tau - 0.5)/3`` are the same number.

    The module docstring derives the lattice viscosity twice — once by
    dimensional scaling, once from ``Re`` — and constraint 2 depends on them
    agreeing.
    """
    u = LatticeUnits.from_physical(
        u_phys=2.0, l_phys=0.2, nu_phys=4e-3, cells_per_length=80.0, u_lattice=0.04
    )
    assert u.to_lattice_viscosity(u.nu_phys) == pytest.approx(u.nu, rel=1e-12)
    assert u.nu == pytest.approx((u.tau - 0.5) / 3.0, rel=1e-12)


def test_re_from_re_and_re_from_nu_agree():
    """Describing the fluid by ``re`` or by ``nu_phys`` gives the same case."""
    a = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, nu_phys=1e-3, cells_per_length=40.0
    )
    b = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=40.0
    )
    assert a.Re == pytest.approx(b.Re)
    assert a.tau == pytest.approx(b.tau)
    assert a.dt == pytest.approx(b.dt)
    assert b.nu_phys == pytest.approx(1e-3)


@pytest.mark.parametrize(
    "u_phys,l_phys,nu_phys,cells",
    [
        (20.0, 1.5, 3.0e-2, 200.0),  # Re 1000, a resolvable wing
        (1.0, 0.1, 1e-3, 60.0),  # Re 100, the Rung 3 regime
        (0.05, 0.002, 1e-6, 30.0),  # Re 100, microfluidic
        (3.0, 0.4, 1.5e-2, 500.0),  # Re 80, well resolved
    ],
)
def test_round_trip_reproduces_re_within_a_tenth_of_a_percent(
    u_phys, l_phys, nu_phys, cells
):
    """physical -> lattice -> physical reproduces Re to within 0.1%.

    ``reynolds()`` recomputes ``Re`` from ``U``, the resolution and ``tau``
    alone — no metres anywhere in that path — so agreement is a statement about
    the conversion, not about arithmetic done twice the same way.
    """
    u = LatticeUnits.from_physical(
        u_phys=u_phys, l_phys=l_phys, nu_phys=nu_phys, cells_per_length=cells
    )
    assert u.reynolds() == pytest.approx(u.Re, rel=1e-3)

    # ... and the physical quantities come back through the other conversions.
    assert u.to_physical_velocity(u.U) == pytest.approx(u_phys, rel=1e-12)
    assert u.to_physical_length(u.cells_per_length) == pytest.approx(l_phys, rel=1e-12)
    back = (
        u.to_physical_velocity(u.U)
        * u.to_physical_length(u.cells_per_length)
        / u.nu_phys
    )
    assert back == pytest.approx(u.Re, rel=1e-3)


def test_time_conversion_round_trips():
    u = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=40.0
    )
    assert u.to_physical_time(u.to_lattice_time(2.5)) == pytest.approx(2.5)
    assert u.to_lattice_length(u.to_physical_length(17.0)) == pytest.approx(17.0)


def test_resolution_is_derived_when_a_target_tau_is_given():
    """The 'derives resolution' half: pass tau, get N — and it inverts exactly."""
    u = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, tau=0.6, u_lattice=0.05
    )
    assert u.tau == pytest.approx(0.6)
    assert u.cells_per_length == pytest.approx(100.0 * 0.1 / (3.0 * 0.05))
    # and going back the other way reproduces the tau that was asked for
    again = LatticeUnits.from_physical(
        u_phys=1.0,
        l_phys=0.1,
        re=100.0,
        cells_per_length=u.cells_per_length,
        u_lattice=0.05,
    )
    assert again.tau == pytest.approx(0.6)


def test_resolution_for_tau_inverts_the_tau_expression():
    u = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=40.0
    )
    n = u.resolution_for_tau(0.54)
    again = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=n, u_lattice=u.U
    )
    assert again.tau == pytest.approx(0.54)


# --- LatticeUnits: what it refuses -------------------------------------------


def test_lattice_velocity_at_the_ceiling_raises_naming_it():
    """Constraint 3 for users: it raises, it does not warn."""
    with pytest.raises(ValueError) as exc:
        LatticeUnits.from_physical(
            u_phys=20.0, l_phys=1.5, re=1000.0, cells_per_length=100.0, u_lattice=0.1
        )
    msg = str(exc.value)
    assert "lattice velocity" in msg.lower()
    assert "constraint 3" in msg
    assert "0.1" in msg


def test_marginal_tau_raises_naming_tau_and_the_resolution_that_fixes_it():
    """The message must carry a number the user can act on."""
    with pytest.raises(ValueError) as exc:
        LatticeUnits.from_physical(
            u_phys=1.0, l_phys=0.1, re=1000.0, cells_per_length=40.0, u_lattice=0.05
        )
    msg = str(exc.value)
    assert "tau" in msg
    assert "cells_per_length >=" in msg

    # The suggested resolution is the one that actually clears the floor.
    suggested = int(msg.split("cells_per_length >=")[1].split(",")[0])
    fixed = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=1000.0, cells_per_length=suggested, u_lattice=0.05
    )
    assert fixed.tau > TAU_FLOOR


def test_the_floor_is_exactly_the_documented_one():
    """tau just above 0.51 is accepted, tau at 0.51 is not."""
    kw = dict(u_phys=1.0, l_phys=0.1, re=100.0, u_lattice=0.05)
    ok = LatticeUnits.from_physical(**kw, tau=TAU_FLOOR + 1e-4)
    assert ok.tau > TAU_FLOOR
    with pytest.raises(ValueError):
        LatticeUnits.from_physical(**kw, tau=TAU_FLOOR)


def test_a_config_between_the_floors_is_accepted_but_says_so():
    """D-029: 0.51 is a floor on nonsense, not a stability guarantee.

    A tau of 0.52 is below the 0.5330 that measurably produced ``nan`` on a
    disc, so it must be accepted (the module cannot know the geometry) *and*
    the note must not imply safety.
    """
    u = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, tau=0.52, u_lattice=0.05
    )
    note = u.stability_note()
    assert "nan" in note.lower() or "blew up" in note.lower()
    assert "D-029" in note
    assert LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, tau=0.60, u_lattice=0.05
    ).stability_note() != note


def test_no_lattice_nu_input_path_exists():
    """Constraint 2: there is no way to set the lattice viscosity directly."""
    import inspect

    params = inspect.signature(LatticeUnits.from_physical).parameters
    assert "nu" not in params
    assert "nu_lattice" not in params
    assert "nu_phys" in params  # the *physical* fluid property is fine


def test_the_fluid_and_the_grid_must_each_be_described_exactly_once():
    with pytest.raises(ValueError, match="fluid exactly once"):
        LatticeUnits.from_physical(
            u_phys=1.0, l_phys=0.1, nu_phys=1e-6, re=100.0, cells_per_length=40.0
        )
    with pytest.raises(ValueError, match="fluid exactly once"):
        LatticeUnits.from_physical(u_phys=1.0, l_phys=0.1, cells_per_length=40.0)
    with pytest.raises(ValueError, match="grid exactly once"):
        LatticeUnits.from_physical(
            u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=40.0, tau=0.6
        )
    with pytest.raises(ValueError, match="grid exactly once"):
        LatticeUnits.from_physical(u_phys=1.0, l_phys=0.1, re=100.0)


@pytest.mark.parametrize(
    "kw",
    [
        dict(u_phys=0.0, l_phys=0.1, re=100.0, cells_per_length=40.0),
        dict(u_phys=1.0, l_phys=-0.1, re=100.0, cells_per_length=40.0),
        dict(u_phys=1.0, l_phys=0.1, nu_phys=0.0, cells_per_length=40.0),
        dict(u_phys=1.0, l_phys=0.1, re=-100.0, cells_per_length=40.0),
        dict(u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=0.0),
        dict(u_phys=1.0, l_phys=0.1, re=100.0, tau=0.5),
        dict(u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=40.0, u_lattice=0.0),
    ],
)
def test_non_physical_inputs_raise(kw):
    with pytest.raises(ValueError):
        LatticeUnits.from_physical(**kw)


def test_peak_velocity_estimate_uses_the_measured_speedup():
    """Session 8 measured peak = 1.79 U past a square; the guard is pessimistic."""
    u = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=40.0, u_lattice=0.05
    )
    assert u.peak_velocity_estimate() == pytest.approx(BLUFF_BODY_SPEEDUP * 0.05)
    assert u.peak_velocity_estimate() < U_LATTICE_MAX  # the default leaves headroom


def test_units_is_frozen():
    """A mutable tau would be a back door around the derivation (constraint 2)."""
    u = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=40.0
    )
    with pytest.raises(Exception):
        u.tau = 0.9  # type: ignore[misc]


def test_summary_prints_the_derivation():
    u = LatticeUnits.from_physical(
        u_phys=20.0, l_phys=1.5, nu_phys=1.5e-1, cells_per_length=200.0
    )
    text = u.summary()
    assert "Re =" in text and "tau = 0.5 + 3 U N / Re" in text and "dt =" in text


def test_dt_is_the_scalar_steps_per_frame_wants():
    """D-023: ``dt`` is seconds per timestep and grid size enters through it.

    Refining by two halves ``dt``, so the same playback speed asks for twice
    the steps — asserted here against the runner's own function, since this
    module is where D-023 says that scalar comes from.
    """
    from lbm.runner import steps_per_frame

    coarse = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=40.0
    )
    fine = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.1, re=100.0, cells_per_length=80.0
    )
    assert fine.dt == pytest.approx(coarse.dt / 2.0)
    assert steps_per_frame(fine.dt) == pytest.approx(
        2 * steps_per_frame(coarse.dt), rel=0.02
    )


def test_the_rung_3_case_comes_out_of_the_units_path():
    """The cylinder of T007, described in physics, gives its lattice numbers.

    ``validate/cylinder.py`` runs a 21-cell disc at ``U = 0.06``, ``Re = 100``,
    and prints ``tau = 0.5378`` and ``dt = (U/U_phys)(D_phys/D_cells)``. Coming
    at the same case from metres and seconds must reproduce both.
    """
    u = LatticeUnits.from_physical(
        u_phys=1.0, l_phys=0.10, re=100.0, cells_per_length=21.0, u_lattice=0.06
    )
    assert u.tau == pytest.approx(0.5378, abs=5e-5)
    assert u.dt == pytest.approx((0.06 / 1.0) * (0.10 / 21.0), rel=1e-12)
    assert u.nu == pytest.approx(0.06 * 21.0 / 100.0, rel=1e-12)


def test_the_physical_path_sets_rung_3_up_identically():
    """``validate.cylinder --physical`` must not be a *different* case.

    The 2% ``Cd`` criterion is measured by running the rung both ways, which
    takes minutes; what this test pins in milliseconds is the reason the two
    runs agree — ``tau``, the lattice ``U`` and ``dt`` come out the same to
    float precision, so the physics being integrated is identical.
    """
    from validate.cylinder import D_PHYS_M, RE, U, U_PHYS_MS, tau_for

    d_measured = 21.0
    nu_ref, tau_ref = tau_for(RE, U, d_measured)
    u = LatticeUnits.from_physical(
        u_phys=U_PHYS_MS,
        l_phys=D_PHYS_M,
        nu_phys=U_PHYS_MS * D_PHYS_M / RE,
        cells_per_length=d_measured,
        u_lattice=U,
    )
    assert u.tau == pytest.approx(tau_ref, rel=1e-12)
    assert u.nu == pytest.approx(nu_ref, rel=1e-12)
    assert u.dt == pytest.approx((U / U_PHYS_MS) * (D_PHYS_M / d_measured), rel=1e-12)
    assert u.Re == pytest.approx(RE, rel=1e-12)


# --- from_png -----------------------------------------------------------------


def test_the_committed_test_png_exists_and_is_small():
    """It is a committed binary; keep it a few kB (prompt, § Before you start)."""
    assert PNG_PATH.exists(), f"{PNG_PATH} is missing — run write_test_png()"
    assert PNG_PATH.stat().st_size < 8192


def test_the_committed_png_is_byte_identical_to_its_generator(tmp_path):
    """The image in the repo is the one this file's arithmetic describes."""
    regenerated = write_test_png(tmp_path / "test_body.png")
    assert regenerated.read_bytes() == PNG_PATH.read_bytes()


def test_solid_cell_count_matches_the_derived_area_within_two_percent():
    """The acceptance criterion, on the committed image."""
    solid = load_png()
    expected = expected_solid_cells()
    count = int(solid.sum())
    assert count == pytest.approx(expected, rel=0.02), (
        f"{count} solid cells against {expected:.1f} expected "
        f"({(count - expected) / expected * 100:+.2f}%)"
    )


def test_the_count_survives_a_non_integer_downscale():
    """Area preservation is a property of the box filter, not of the factor 2."""
    solid = from_png(PNG_PATH, (97, 97), check=False, verbose=False)
    expected = expected_solid_cells(97, 97)
    assert int(solid.sum()) == pytest.approx(expected, rel=0.02)


def test_from_png_returns_a_bool_array_of_the_requested_shape():
    solid = load_png()
    assert solid.shape == GRID
    assert solid.dtype == np.bool_


def test_alpha_is_preferred_over_luminance(tmp_path, capsys):
    """A white shape on a transparent field: luminance would see nothing.

    The image is white-on-transparent, so the luminance path (dark = solid)
    would return an *empty* mask. Getting the disc back is the proof that alpha
    won.
    """
    from_png(PNG_PATH, GRID, check=False, verbose=True)
    assert "alpha" in capsys.readouterr().out

    # ``invert`` flips the sense of that same alpha channel, so the two masks
    # are complements up to the cells sitting exactly on the threshold.
    normal = load_png()
    forced = from_png(PNG_PATH, GRID, check=False, verbose=False, invert=True)
    assert not (normal & forced).any()
    assert forced.sum() == pytest.approx(
        GRID[0] * GRID[1] - normal.sum(), rel=0.01
    )


def test_luminance_fallback_when_there_is_no_alpha(tmp_path):
    """A plain black-on-white image, no alpha channel: dark is solid."""
    from PIL import Image

    a = np.full((64, 64), 255, dtype=np.uint8)
    a[16:48, 8:24] = 0  # a black block, 32 x 16 px
    path = tmp_path / "gray.png"
    Image.fromarray(a, mode="L").save(path)

    solid = from_png(path, (64, 64), check=False, verbose=False)
    assert int(solid.sum()) == 32 * 16
    # flip_y is on by default, so the block's rows are mirrored.
    assert solid[64 - 48 : 64 - 16, 8:24].all()


def test_a_fully_opaque_rgba_image_falls_back_to_luminance(tmp_path):
    """Alpha that is uniformly opaque carries no shape and must not be used."""
    from PIL import Image

    rgba = np.zeros((32, 32, 4), dtype=np.uint8)
    rgba[..., 3] = 255
    rgba[..., :3] = 255
    rgba[8:24, 8:24, :3] = 0  # a dark square
    path = tmp_path / "opaque.png"
    Image.fromarray(rgba, mode="RGBA").save(path)

    solid = from_png(path, (32, 32), check=False, verbose=False)
    assert int(solid.sum()) == 16 * 16


def test_flip_y_is_what_makes_the_picture_upright():
    """Image row 0 is the top; the solver's y increases upward (LiveSink)."""
    up = load_png(flip_y=True)
    down = load_png(flip_y=False)
    assert np.array_equal(up, down[::-1, :])

    # The rectangle sits near the *top* of the picture (y = 40..60 of 256), so
    # with flip_y it must land in the upper rows of the mask.
    tail_up = np.flatnonzero(up[:, GRID[1] // 2 + 40 :].any(axis=1))
    assert tail_up.mean() > GRID[0] / 2


def test_threshold_moves_the_boundary_the_way_it_should():
    """A higher threshold keeps only cells the shape covers more fully."""
    lo = load_png(threshold=0.2)
    hi = load_png(threshold=0.8)
    assert lo.sum() >= hi.sum()
    assert np.all(hi <= lo)  # the strict mask is a subset


def test_contain_preserves_the_aspect_ratio(tmp_path):
    """``fit='contain'`` pads with fluid instead of distorting the shape."""
    from PIL import Image

    rgba = np.zeros((64, 64, 4), dtype=np.uint8)
    rgba[..., :3] = 255
    rgba[16:48, 16:48, 3] = 255  # a 32 x 32 square
    path = tmp_path / "square.png"
    Image.fromarray(rgba, mode="RGBA").save(path)

    solid = from_png(path, (64, 128), fit="contain", check=False, verbose=False)
    box = bounding_box(solid)
    assert box is not None
    y0, y1, x0, x1 = box
    assert (y1 - y0 + 1) == pytest.approx(x1 - x0 + 1, abs=1)  # still square

    stretched = from_png(path, (64, 128), fit="stretch", check=False, verbose=False)
    sbox = bounding_box(stretched)
    assert sbox is not None
    assert (sbox[3] - sbox[2] + 1) > (sbox[1] - sbox[0] + 1)  # and this one is not


def test_check_mask_runs_automatically(recwarn):
    """Constraint 12: ``from_png`` calls ``check_mask`` itself.

    The committed image is a 64-cell body in a 128-row grid — 50% blockage —
    so a clean load *must* warn. That the warning appears without the caller
    asking for it is the criterion.
    """
    from_png(PNG_PATH, GRID, verbose=False)
    assert any(issubclass(w.category, MaskWarning) for w in recwarn)


def test_check_can_be_turned_off_and_strict_raises():
    with warnings.catch_warnings():
        warnings.simplefilter("error", MaskWarning)
        from_png(PNG_PATH, GRID, check=False, verbose=False)  # no warning at all
    with pytest.raises(ValueError, match="check_mask failed"):
        from_png(PNG_PATH, GRID, check=True, strict=True, verbose=False)


def test_a_hairline_png_is_caught_by_the_thickness_rule(tmp_path):
    """The failure this criterion exists for: a downscale that thins a wall.

    A 6-pixel-wide bar in a 256-px image is a 1.5-cell feature at 64 cells.
    Whatever survives the threshold is thinner than the 3 cells constraint 12
    demands, and ``check_mask`` says so before the run.
    """
    from PIL import Image

    rgba = np.zeros((256, 256, 4), dtype=np.uint8)
    rgba[..., :3] = 255
    rgba[40:216, 124:130, 3] = 255  # a 6-px-wide vertical bar
    path = tmp_path / "hairline.png"
    Image.fromarray(rgba, mode="RGBA").save(path)

    solid = from_png(path, (64, 64), check=False, verbose=False)
    assert solid.any(), "the bar vanished entirely; the test needs a wider bar"
    assert min_thickness(solid) < 3

    with pytest.warns(MaskWarning, match="cells thick"):
        from_png(path, (64, 64), verbose=False)


def test_a_missing_file_says_so():
    with pytest.raises(FileNotFoundError):
        from_png(DATA / "does_not_exist.png", GRID, verbose=False)


@pytest.mark.parametrize(
    "kw",
    [
        dict(shape=(0, 10)),
        dict(shape=(10, 10), threshold=1.5),
        dict(shape=(10, 10), fit="squash"),
    ],
)
def test_bad_png_arguments_raise(kw):
    shape = kw.pop("shape")
    with pytest.raises(ValueError):
        from_png(PNG_PATH, shape, check=False, verbose=False, **kw)


# --- from_svg -----------------------------------------------------------------


SQUARE_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path d="M 20 20 L 80 20 L 80 80 L 20 80 Z"/>
</svg>
"""


def write_svg(tmp_path: Path, text: str, name: str = "shape.svg") -> Path:
    path = tmp_path / name
    path.write_text(text, encoding="utf-8")
    return path


def test_a_simple_closed_path_rasterises(tmp_path):
    """The acceptance criterion's 'at least simple closed paths'.

    The square covers 60/100 of the viewBox in each direction, so on a 101-cell
    grid fitted to the viewBox it spans about 61 cells and covers about 36% of
    the grid.
    """
    solid = from_svg(
        write_svg(tmp_path, SQUARE_SVG), (101, 101), check=False, verbose=False
    )
    assert solid.dtype == np.bool_ and solid.shape == (101, 101)
    box = bounding_box(solid)
    assert box is not None
    y0, y1, x0, x1 = box
    assert (y1 - y0 + 1) == pytest.approx(61, abs=2)
    assert (x1 - x0 + 1) == pytest.approx(61, abs=2)
    assert int(solid.sum()) == pytest.approx(61 * 61, rel=0.05)


def test_relative_commands_and_shorthands_give_the_same_square(tmp_path):
    """``m/h/v/z`` describe the same shape as ``M/L/Z``."""
    rel = """<svg viewBox="0 0 100 100"><path d="m 20 20 h 60 v 60 h -60 z"/></svg>"""
    a = from_svg(
        write_svg(tmp_path, SQUARE_SVG, "abs.svg"), (101, 101),
        check=False, verbose=False,
    )
    b = from_svg(
        write_svg(tmp_path, rel, "rel.svg"), (101, 101), check=False, verbose=False
    )
    assert np.array_equal(a, b)


def test_a_polygon_element_is_read_too(tmp_path):
    poly = """<svg viewBox="0 0 100 100">
      <polygon points="20,20 80,20 80,80 20,80"/></svg>"""
    a = from_svg(
        write_svg(tmp_path, SQUARE_SVG, "p.svg"), (101, 101), check=False, verbose=False
    )
    b = from_svg(
        write_svg(tmp_path, poly, "q.svg"), (101, 101), check=False, verbose=False
    )
    assert np.array_equal(a, b)


def test_curves_are_flattened(tmp_path):
    """A cubic-Bezier circle approximation comes out round, not empty."""
    k = 0.5523 * 40.0
    circle_svg = f"""<svg viewBox="0 0 100 100"><path d="
      M 90 50 C 90 {50 + k} {50 + k} 90 50 90 C {50 - k} 90 10 {50 + k} 10 50
      C 10 {50 - k} {50 - k} 10 50 10 C {50 + k} 10 90 {50 - k} 90 50 Z"/></svg>"""
    solid = from_svg(
        write_svg(tmp_path, circle_svg, "circle.svg"), (101, 101),
        check=False, verbose=False,
    )
    # A disc of radius 40 in a 100-unit viewBox scaled to 101 cells: area
    # pi r^2 with r ~ 40 cells.
    assert int(solid.sum()) == pytest.approx(math.pi * 40.0**2, rel=0.05)
    box = bounding_box(solid)
    assert box is not None
    assert (box[1] - box[0] + 1) == pytest.approx(box[3] - box[2] + 1, abs=2)


def test_two_subpaths_make_a_hole(tmp_path):
    """Even-odd across subpaths — the documented fill rule."""
    donut = """<svg viewBox="0 0 100 100">
      <path d="M 10 10 L 90 10 L 90 90 L 10 90 Z"/>
      <path d="M 40 40 L 60 40 L 60 60 L 40 60 Z"/></svg>"""
    solid = from_svg(
        write_svg(tmp_path, donut, "donut.svg"), (101, 101), check=False, verbose=False
    )
    assert not solid[50, 50]  # the hole
    assert solid[50, 15]  # the ring


def test_unsupported_features_raise_an_install_message(tmp_path):
    """Not a silent partial render — arcs and transforms name cairosvg."""
    arc = """<svg viewBox="0 0 100 100">
      <path d="M 20 50 A 30 30 0 1 1 80 50 Z"/></svg>"""
    with pytest.raises(ImportError, match="cairosvg"):
        from_svg(write_svg(tmp_path, arc, "arc.svg"), (64, 64), verbose=False)

    transformed = """<svg viewBox="0 0 100 100">
      <path transform="rotate(30)" d="M 20 20 L 80 20 L 80 80 Z"/></svg>"""
    with pytest.raises(ImportError, match="cairosvg"):
        from_svg(write_svg(tmp_path, transformed, "t.svg"), (64, 64), verbose=False)


def test_an_svg_with_nothing_fillable_says_so(tmp_path):
    empty = """<svg viewBox="0 0 10 10"><text x="1" y="1">hello</text></svg>"""
    with pytest.raises(ValueError, match="nothing to rasterise"):
        from_svg(write_svg(tmp_path, empty, "text.svg"), (32, 32), verbose=False)


def test_missing_svg_file_raises():
    with pytest.raises(FileNotFoundError):
        from_svg(DATA / "nope.svg", (32, 32), verbose=False)


def test_svg_check_mask_runs_automatically(tmp_path):
    """Same constraint-12 rule as ``from_png``: the check is not optional."""
    with pytest.warns(MaskWarning):
        from_svg(write_svg(tmp_path, SQUARE_SVG), (101, 101), verbose=False)


def test_svg_flip_y_matches_png(tmp_path):
    """SVG's y points down; the solver's points up."""
    wedge = """<svg viewBox="0 0 100 100">
      <path d="M 10 10 L 90 10 L 50 40 Z"/></svg>"""
    path = write_svg(tmp_path, wedge, "wedge.svg")
    raw = from_svg(path, (101, 101), check=False, verbose=False, flip_y=False)
    down = from_svg(path, (101, 101), check=False, verbose=False, flip_y=True)

    # The wide edge is at SVG y = 10, i.e. the top of the picture. Unflipped it
    # lands in the low rows of the mask (which the renderer draws at the
    # bottom); flipped, in the high rows. The two masks are not asserted to be
    # exact mirrors: the flip happens in *coordinates*, before the even-odd
    # fill, and that fill's tie-breaking is not symmetric to the cell.
    def widest_row(mask: np.ndarray) -> int:
        return int(np.argmax(mask.sum(axis=1)))

    assert widest_row(raw) < 101 / 2 < widest_row(down)
    # Same shape either way, to within the one boundary row that even-odd's
    # half-open span rule includes on one side of the reflection and not the
    # other — the wedge's flat edge is exactly that row.
    assert abs(int(raw.sum()) - int(down.sum())) <= int(raw.sum(axis=1).max())
